// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Pod extends pulumi.CustomResource {
    /**
     * Get an existing Pod resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Pod {
        return new Pod(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'runpod:index:Pod';

    /**
     * Returns true if the given object is an instance of Pod.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Pod {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Pod.__pulumiType;
    }

    public readonly cloudType!: pulumi.Output<string>;
    public readonly gpuCount!: pulumi.Output<number>;
    public readonly gpuTypeId!: pulumi.Output<string>;

    /**
     * Create a Pod resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PodArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.cloudType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'cloudType'");
            }
            if ((!args || args.gpuCount === undefined) && !opts.urn) {
                throw new Error("Missing required property 'gpuCount'");
            }
            if ((!args || args.gpuTypeId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'gpuTypeId'");
            }
            resourceInputs["cloudType"] = args ? args.cloudType : undefined;
            resourceInputs["gpuCount"] = args ? args.gpuCount : undefined;
            resourceInputs["gpuTypeId"] = args ? args.gpuTypeId : undefined;
        } else {
            resourceInputs["cloudType"] = undefined /*out*/;
            resourceInputs["gpuCount"] = undefined /*out*/;
            resourceInputs["gpuTypeId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Pod.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Pod resource.
 */
export interface PodArgs {
    cloudType: pulumi.Input<string>;
    gpuCount: pulumi.Input<number>;
    gpuTypeId: pulumi.Input<string>;
}
